name: Gather data and update statistics MD file 
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run data gathering script
      run: |
        cd scripts; python gather_data.py
        ls -l --block-size=M ../data/data.db
    - name: Run statistics generation script
      run: |
        cd scripts; python generate_stats_md_file.py
    - name: Set up Git user
      run: git config --global user.email "gha@github.com"; git config --global user.name "GHActionBot"
    - name: Commit update
      run: git commit -am "Sync stats data"; git push
    - name: Attach generated artefacts      
      uses: actions/upload-artifact@v3
      with:
        name: data
        path: |
          data/data.db
          data/input.csv
          stats.md